const tabs=['Dashboard','Inspection','Temperatures','Equipment','Maintenance','Events','Incidents','Documents','Team','Settings'];
const E=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const C=(h,b)=>'<section class="card"><h3>'+h+'</h3>'+b+'</section>',L=(a,f)=>a.length?a.map(f).join(''):'<p class="muted">No records yet.</p>';
const sb=supabase.createClient(KAKO_CLOUD.supabaseUrl,KAKO_CLOUD.supabaseAnonKey);
let user=null,profile=null,truck=null,t='Dashboard',d={inspection:[],temps:[],equipment:[],maintenance:[],events:[],incidents:[],documents:[]};
function nav(){document.getElementById('nav').innerHTML=user?tabs.map(x=>'<button class="tab '+(x===t?'active':'')+'" onclick="t=\''+x+'\';R()">'+x+'</button>').join(''):''}
async function login(){let email=document.getElementById('email').value,password=document.getElementById('password').value,msg=document.getElementById('msg');msg.textContent='Signing in…';let {error}=await sb.auth.signInWithPassword({email,password});if(error){msg.textContent=error.message;return}await boot()}
async function logout(){await sb.auth.signOut();user=null;profile=null;truck=null;R()}
async function boot(){let {data:{user:u}}=await sb.auth.getUser();user=u;if(!user){R();return}let p=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();profile=p.data;let tr=await sb.from('trucks').select('*').order('created_at',{ascending:true}).limit(1).maybeSingle();truck=tr.data;if(!truck){document.getElementById('app').innerHTML=C('Setup problem','Truck record not found.');return}await load();R()}
async function load(){let id=truck.id;let [e,i,tp,m,ev,inc,doc]=await Promise.all([sb.from('equipment').select('*').eq('truck_id',id).order('created_at'),sb.from('inspections').select('*').eq('truck_id',id).order('created_at',{ascending:false}).limit(100),sb.from('temperature_logs').select('*').eq('truck_id',id).order('created_at',{ascending:false}).limit(100),sb.from('maintenance').select('*').eq('truck_id',id).order('created_at',{ascending:false}),sb.from('events').select('*').eq('truck_id',id).order('event_date',{ascending:false}),sb.from('incidents').select('*').eq('truck_id',id).order('created_at',{ascending:false}),sb.from('documents').select('*').eq('truck_id',id).order('created_at',{ascending:false})]);d={equipment:e.data||[],inspection:i.data||[],temps:tp.data||[],maintenance:m.data||[],events:ev.data||[],incidents:inc.data||[],documents:doc.data||[]}}
function status(){if(d.equipment.some(x=>x.critical&&x.status==='FAIL')||d.inspection.some(x=>x.critical&&x.result==='FAIL'))return'DO NOT OPERATE';if(d.equipment.some(x=>x.status==='SERVICE')||d.inspection.some(x=>!x.critical&&x.result==='FAIL')||d.maintenance.some(x=>x.status==='Open'))return'ACTION REQUIRED';return'READY'}
async function addInspection(){let item=i.value.trim();if(!item)return;let {error}=await sb.from('inspections').insert({truck_id:truck.id,user_id:user.id,item,result:r.value,critical:c.value==='true',notes:n.value});if(error)return alert(error.message);await load();R()}
async function addTemp(){if(!w.value||!p.value)return;let {error}=await sb.from('temperature_logs').insert({truck_id:truck.id,user_id:user.id,location:w.value,temp_f:Number(p.value),notes:n.value});if(error)return alert(error.message);await load();R()}
async function addMaint(){if(!a.value)return;let {error}=await sb.from('maintenance').insert({truck_id:truck.id,title:a.value,due_date:b.value||null,status:c.value,notes:n.value});if(error)return alert(error.message);await load();R()}
async function addEvent(){if(!a.value)return;let {error}=await sb.from('events').insert({truck_id:truck.id,name:a.value,event_date:b.value||null,location:c.value,notes:n.value});if(error)return alert(error.message);await load();R()}
async function addIncident(){if(!a.value)return;let {error}=await sb.from('incidents').insert({truck_id:truck.id,user_id:user.id,title:a.value,severity:b.value,description:c.value,action_taken:n.value});if(error)return alert(error.message);await load();R()}
async function addDoc(){if(!a.value)return;let {error}=await sb.from('documents').insert({truck_id:truck.id,name:a.value,expires_on:b.value||null,reference:c.value});if(error)return alert(error.message);await load();R()}
async function setEquipment(id,val){let {error}=await sb.from('equipment').update({status:val}).eq('id',id);if(error)return alert(error.message);await load();R()}
async function saveTruck(){let {error}=await sb.from('trucks').update({mileage:Number(mileage.value||0)}).eq('id',truck.id);if(error)return alert(error.message);truck.mileage=Number(mileage.value||0);R()}
function R(){nav();let app=document.getElementById('app');if(!user){app.innerHTML='<div class="login">'+C('Owner Sign In','<p class="muted">Use the Supabase owner account you created.</p><label>Email</label><input id="email" type="email" autocomplete="username"><label>Password</label><input id="password" type="password" autocomplete="current-password"><button onclick="login()">Sign in</button><p id="msg" class="error"></p>')+'</div>';return}
let s=status(),cl=s==='READY'?'READY':s==='ACTION REQUIRED'?'ACTION':'STOP';
if(t==='Dashboard')app.innerHTML='<div class="status '+cl+'">'+s+'</div><br><div class="grid">'+C('Truck','<b>'+E(truck.name)+'</b><p class="muted">Mileage: '+E(truck.mileage)+'</p>')+C('Cloud','<span class="ok">Connected</span><p class="muted">Signed in as '+E(profile?.full_name||user.email)+'</p>')+C('Open Maintenance','<b style="font-size:30px">'+d.maintenance.filter(x=>x.status==='Open').length+'</b>')+C('Latest Temperature',d.temps.length?'<b style="font-size:26px">'+E(d.temps[0].temp_f)+'°F</b><p>'+E(d.temps[0].location)+'</p>':'<p class="muted">No temperature recorded.</p>')+'</div>';
if(t==='Inspection')app.innerHTML='<h2>Pre-Departure Inspection</h2>'+C('New Check','<input id=i placeholder="Inspection item"><select id=r><option>PASS</option><option>FAIL</option></select><select id=c><option value=true>Critical</option><option value=false>Noncritical</option></select><textarea id=n placeholder="Notes"></textarea><button onclick="addInspection()">Save to cloud</button>')+C('History',L(d.inspection,x=>'<div class=item><b>'+E(x.item)+'</b> — '+x.result+' '+(x.critical?'<span class=critical>CRITICAL</span>':'')+'<div class=muted>'+new Date(x.created_at).toLocaleString()+' '+E(x.notes)+'</div></div>'));
if(t==='Temperatures')app.innerHTML='<h2>Temperature Log</h2>'+C('Record','<input id=w placeholder="Location / food"><input id=p inputmode=decimal placeholder="Temperature °F"><input id=n placeholder="Notes / corrective action"><button onclick="addTemp()">Save to cloud</button>')+C('History',L(d.temps,x=>'<div class=item><b>'+E(x.location)+' — '+E(x.temp_f)+'°F</b><div class=muted>'+new Date(x.created_at).toLocaleString()+' '+E(x.notes)+'</div></div>'));
if(t==='Equipment')app.innerHTML='<h2>Equipment</h2>'+(!d.equipment.length?C('Equipment setup','<p class=muted>No cloud equipment records yet. We will seed your truck equipment next.</p>'):'<div class=grid>'+d.equipment.map(x=>C(E(x.name),(x.critical?'<span class=critical>Critical system</span>':'<span class=muted>Noncritical</span>')+'<select onchange="setEquipment(\''+x.id+'\',this.value)"><option '+(x.status==='OK'?'selected':'')+'>OK</option><option '+(x.status==='SERVICE'?'selected':'')+'>SERVICE</option><option '+(x.status==='FAIL'?'selected':'')+'>FAIL</option></select>')).join('')+'</div>');
if(t==='Maintenance')app.innerHTML='<h2>Maintenance</h2>'+C('New Item','<input id=a placeholder="Issue / service"><input id=b type=date><select id=c><option>Open</option><option>Completed</option></select><textarea id=n placeholder=Notes></textarea><button onclick="addMaint()">Save to cloud</button>')+C('Log',L(d.maintenance,x=>'<div class=item><b>'+E(x.title)+'</b> — '+E(x.status)+'<div class=muted>Due '+E(x.due_date||'—')+' • '+E(x.notes)+'</div></div>'));
if(t==='Events')app.innerHTML='<h2>Events</h2>'+C('Add Event','<input id=a placeholder="Event / client"><input id=b type=date><input id=c placeholder=Location><textarea id=n placeholder="Setup notes"></textarea><button onclick="addEvent()">Save to cloud</button>')+C('Log',L(d.events,x=>'<div class=item><b>'+E(x.name)+'</b><div>'+E(x.event_date||'')+' • '+E(x.location)+'</div><div class=muted>'+E(x.notes)+'</div></div>'));
if(t==='Incidents')app.innerHTML='<h2>Incident / Breakdown Reports</h2>'+C('New Report','<input id=a placeholder=Title><select id=b><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select><textarea id=c placeholder="What happened?"></textarea><textarea id=n placeholder="Action taken"></textarea><button onclick="addIncident()">Save to cloud</button>')+C('Reports',L(d.incidents,x=>'<div class=item><b>'+E(x.title)+'</b> — '+E(x.severity)+'<div>'+E(x.description)+'</div><div class=muted>Action: '+E(x.action_taken)+'</div></div>'));
if(t==='Documents')app.innerHTML='<h2>Permits & Documents</h2>'+C('Track Document','<input id=a placeholder="Permit / COI / document"><input id=b type=date><input id=c placeholder="Issuer / reference"><button onclick="addDoc()">Save to cloud</button>')+C('Register',L(d.documents,x=>'<div class=item><b>'+E(x.name)+'</b><div class=muted>Expires '+E(x.expires_on||'—')+' • '+E(x.reference)+'</div></div>'));
if(t==='Team')app.innerHTML='<h2>Team & Roles</h2>'+C('Your Account','<b>'+E(profile?.full_name||user.email)+'</b><p class=muted>Role: '+E(profile?.role||'owner')+'</p><p class=muted>Employee invitations and role restrictions are the next security phase.</p>');
if(t==='Settings')app.innerHTML='<h2>Settings</h2><div class=grid>'+C('Truck Profile','<label>Mileage</label><input id=mileage inputmode=numeric value="'+E(truck.mileage)+'"><button onclick="saveTruck()">Save to cloud</button>')+C('Cloud Status','<span class=ok>Supabase connected</span><p class=muted>'+E(user.email)+'</p>')+C('Account','<button onclick="logout()">Sign out</button>')+'</div>'}
sb.auth.onAuthStateChange(()=>{});boot();